import type { ClothingItem } from '../../module/NPCSidebarPortrait';

export const Clothing = {
  double_breasted_jacket: {
    index: 97,
    slot: 'upper',
    name: 'double breasted jacket',
    variable: 'doublebreasted',
    integrity: 200,
    reveal: 400,
    one_piece: 0,
    open: 0,
    state: 'waist',
    state_top: 'chest',
    plural: 0,
    colour: 'black',
    exposed: 0,
    type: ['formal', 'bellyHide'],
    set: 'upper',
    gender: 'm',
    warmth: 8,
    accessory: 1,
    accessory_colour: 'pale white',
    cursed: 0,
    location: 0,
    pregType: 'min',
    colour_sidebar: 1,
    accessory_colour_sidebar: 1,
    cn_name_cap: '双排扣夹克',
    lastTaken: 'wardrobe'
  },
  lace_bra: {
    index: 10,
    slot: 'under_upper',
    name: 'lace bra',
    variable: 'lacebra',
    integrity: 80,
    reveal: 600,
    one_piece: 0,
    open: 1,
    state: 'midriff',
    state_top: 'chest',
    plural: 0,
    colour: 'pale white',
    exposed: 0,
    type: ['normal'],
    set: 'under_upper',
    gender: 'f',
    warmth: 1,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    mainImage: 0,
    colour_sidebar: 1,
    cn_name_cap: '蕾丝胸罩',
    accessory_colour_sidebar: 0,
    lastTaken: 'wardrobe'
  },
  lace_panties: {
    index: 3,
    slot: 'under_lower',
    name: 'lace panties',
    variable: 'lacepanties',
    integrity: 60,
    reveal: 600,
    one_piece: 0,
    state: 'waist',
    plural: 1,
    colour: 'pale white',
    exposed: 0,
    type: ['normal'],
    set: 'under_lower',
    gender: 'f',
    warmth: 1,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    rearresize: 0,
    vagina_exposed: 0,
    anus_exposed: 0,
    high_img: 0,
    name_simple: '内裤',
    anal_shield: 0,
    penis_img: 0,
    cn_name_cap: '蕾丝内裤',
    accessory_colour_sidebar: 0,
    lastTaken: 'wardrobe'
  },
  briefs: {
    index: 4,
    slot: 'under_lower',
    name: 'briefs',
    variable: 'briefs',
    integrity: 100,
    reveal: 400,
    one_piece: 0,
    state: 'waist',
    plural: 1,
    colour: 'pale white',
    exposed: 0,
    type: ['normal'],
    set: 'under_lower',
    gender: 'm',
    warmth: 1,
    accessory: 1,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    accessory_colour_combat: 'white',
    rearresize: 0,
    vagina_exposed: 0,
    anus_exposed: 0,
    high_img: 0,
    name_simple: '内裤',
    anal_shield: 0,
    penis_img: 0,
    no_aside: 1,
    cn_name_cap: '三角裤',
    accessory_colour_sidebar: 0,
    lastTaken: 'wardrobe'
  },
  mini_snowman: {
    index: 37,
    slot: 'head',
    name: 'mini snowman',
    variable: 'minisnowman',
    integrity: 100,
    reveal: 1,
    one_piece: 0,
    state: 0,
    plural: 0,
    colour: 0,
    type: ['costume'],
    gender: 'n',
    warmth: 0,
    accessory: 0,
    accessory_colour: 0,
    colour_combat: 0,
    hood: 0,
    cn_name_cap: '小雪人',
    colour_sidebar: 0,
    accessory_colour_sidebar: 0
  },
  hairpin: {
    index: 1,
    slot: 'head',
    name: 'hairpin',
    cn_name_cap: '发卡',
    variable: 'hairpin',
    state: 0,
    integrity: 50,
    reveal: 1,
    plural: 0,
    colour: 'white',
    type: ['normal'],
    gender: 'f',
    warmth: 0,
    accessory: 1,
    accessory_colour: 'white',
    back_img: 0,
    cursed: 0,
    location: 0,
    accessory_colour_sidebar: 1,
    colour_combat: 0,
    colour_sidebar: 1
  },
  rose_eyepatch: {
    index: 46,
    slot: 'face',
    name: 'rose eyepatch',
    cn_name_cap: '玫瑰眼罩',
    variable: 'rose eyepatch',
    state: 0,
    integrity: 100,
    reveal: 200,
    plural: 0,
    colour: 'white',
    colour_sidebar: 1,
    type: ['formal', 'costume'],
    gender: 'n',
    warmth: 0,
    accessory: 1,
    accessory_colour: 'red',
    accessory_colour_sidebar: 1,
    altposition: 'none',
    altdisabled: [],
    cursed: 0,
    location: 0
  },
  flower_crown: {
    index: 14,
    slot: 'head',
    name: 'flower crown',
    cn_name_cap: '花环',
    variable: 'flower',
    state: 0,
    integrity: 50,
    reveal: 1,
    plural: 0,
    colour: 0,
    colour_combat: 0,
    type: ['normal'],
    gender: 'f',
    warmth: 0,
    accessory: 0,
    accessory_colour: 0,
    back_img: 'combat',
    cursed: 0,
    location: 0
  },
  glasses: {
    index: 1,
    slot: 'face',
    name: 'glasses',
    cn_name_cap: '眼镜',
    variable: 'glasses',
    state: 0,
    integrity: 20,
    reveal: 1,
    plural: 1,
    colour: 'red',
    colour_sidebar: 1,
    colour_combat: 0,
    type: ['glasses'],
    gender: 'n',
    warmth: 0,
    accessory: 1,
    accessory_colour: 0,
    altposition: 'none',
    altdisabled: [],
    cursed: 0,
    location: 0
  },
  holy_pendant: {
    index: 3,
    slot: 'neck',
    name: 'holy pendant',
    cn_name_cap: '十字架',
    variable: 'holypendant',
    state: 0,
    integrity: 100,
    reveal: 1,
    plural: 0,
    colour: 0,
    colour_combat: 'yellow',
    type: ['holy'],
    gender: 'n',
    warmth: 0,
    collared: 0,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0
  },
  sage_witch_hat: {
    index: 86,
    slot: 'head',
    name: 'sage witch hat',
    variable: 'witchsage',
    integrity: 200,
    reveal: 1,
    one_piece: 0,
    state: 0,
    plural: 0,
    colour: 0,
    type: ['costume', 'shade', 'esoteric', 'hat'],
    gender: 'n',
    warmth: 2,
    accessory: 1,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    mask_img: 1,
    colour_combat: 0,
    back_img: 1,
    cn_name_cap: '贤者巫师帽',
    set: 'head',
    colour_sidebar: 0,
    accessory_colour_sidebar: 0
  },
  jasper_pendant: {
    index: 39,
    slot: 'neck',
    name: 'jasper pendant',
    variable: 'jasperpendant',
    integrity: 100,
    reveal: 50,
    one_piece: 0,
    state: 0,
    plural: 0,
    colour: 0,
    type: ['eerie'],
    gender: 'n',
    warmth: 0,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    colour_combat: 'red',
    collared: 0,
    cn_name_cap: '碧玉吊坠',
    set: 'neck',
    colour_sidebar: 0,
    accessory_colour_sidebar: 0
  },
  scarf: {
    index: 16,
    slot: 'neck',
    name: 'scarf',
    variable: 'scarf',
    state: 0,
    integrity: 100,
    reveal: 100,
    plural: 0,
    colour: 'green',
    type: ['normal'],
    gender: 'n',
    warmth: 4,
    collared: 0,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    zIndex: 'head',
    colour_sidebar: 1,
    cn_name_cap: '围巾',
    set: 'neck',
    accessory_colour_sidebar: 0
  },
  cable_knit_turtleneck: {
    index: 43,
    slot: 'upper',
    name: 'cable knit turtleneck',
    variable: 'cable',
    integrity: 150,
    reveal: 300,
    one_piece: 0,
    open: 0,
    state: 'waist',
    state_top: 'chest',
    plural: 0,
    colour: 'green',
    type: ['normal', 'bellyHide'],
    set: 'upper',
    gender: 'n',
    warmth: 8,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    pregType: 'min',
    colour_sidebar: 1,
    cn_name_cap: '线织高领毛衣',
    accessory_colour_sidebar: 0
  },
  off_shoulder_sweater_dress_upper: {
    index: 226,
    slot: 'upper',
    name: 'off-shoulder sweater dress',
    variable: 'offshoulder sweater dress',
    integrity: 100,
    reveal: 500,
    one_piece: 1,
    open: 0,
    state: 'waist',
    state_top: 'chest',
    plural: 0,
    colour: 'olive',
    type: ['normal'],
    set: 'off-shoulder sweater dress',
    gender: 'f',
    warmth: 8,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    outfitPrimary: { lower: 'off-shoulder sweater dress' },
    cn_name_cap: '一字肩毛衣连衣裙',
    accessory_colour_sidebar: 0
  },
  off_shoulder_sweater_dress_lower: {
    index: 212,
    slot: 'lower',
    name: 'off-shoulder sweater dress',
    variable: 'offshoulder sweater dress',
    integrity: 100,
    reveal: 200,
    one_piece: 1,
    state: 'waist',
    plural: 0,
    colour: 'olive',
    type: ['normal', 'bellyHide'],
    set: 'off-shoulder sweater dress',
    gender: 'f',
    warmth: 2,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    outfitSecondary: ['upper', 'off-shoulder sweater dress'],
    skirt_down: 1,
    vagina_exposed: 0,
    anus_exposed: 0,
    cn_name_cap: '一字肩毛衣连衣裙',
    accessory_colour_sidebar: 0
  },
  floral_sundress_upper: {
    index: 232,
    slot: 'upper',
    name: 'floral sundress',
    variable: 'floral sundress',
    integrity: 50,
    reveal: 400,
    one_piece: 1,
    state: 'waist',
    state_top: 'chest',
    plural: 0,
    colour: 'light pink',
    type: ['formal'],
    gender: 'f',
    warmth: 2,
    accessory: 1,
    accessory_colour: 'white',
    cursed: 0,
    location: 0,
    outfitPrimary: { lower: 'floral sundress' },
    pattern: 'leaves',
    pattern_options: ['leaves'],
    pattern_layer: 'tertiary',
    accessory_integrity_img: 1,
    detailIcon: 'floral-sundress-leaves.png',
    cn_name_cap: '碎花夏日连衣裙',
    pattern_options_cn_name: ['叶子'],
    set: 'floral sundress',
    colour_sidebar: 1,
    accessory_colour_sidebar: 1
  },
  floral_sundress_lower: {
    index: 217,
    slot: 'lower',
    name: 'floral sundress',
    variable: 'floral sundress',
    integrity: 50,
    reveal: 400,
    one_piece: 1,
    state: 'waist',
    plural: 0,
    colour: 'light pink',
    type: ['formal'],
    gender: 'f',
    warmth: 3,
    accessory: 1,
    accessory_colour: 'white',
    cursed: 0,
    location: 0,
    outfitSecondary: ['upper', 'floral sundress'],
    accessory_integrity_img: 1,
    vagina_exposed: 0,
    anus_exposed: 0,
    cn_name_cap: '碎花夏日连衣裙',
    set: 'floral sundress',
    colour_sidebar: 1,
    accessory_colour_sidebar: 1
  },
  frilled_sundress_upper: {
    index: 233,
    slot: 'upper',
    name: 'frilled sundress',
    variable: 'frilled sundress',
    integrity: 50,
    reveal: 300,
    one_piece: 1,
    state: 'waist',
    state_top: 'chest',
    plural: 0,
    colour: 'white',
    type: ['normal'],
    gender: 'f',
    warmth: 2,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    outfitPrimary: { lower: 'frilled sundress' },
    cn_name_cap: '荷叶边夏日连衣裙',
    set: 'frilled sundress',
    colour_sidebar: 1,
    accessory_colour_sidebar: 0
  },
  frilled_sundress_lower: {
    index: 218,
    slot: 'lower',
    name: 'frilled sundress',
    variable: 'frilled sundress',
    integrity: 50,
    reveal: 300,
    one_piece: 1,
    state: 'waist',
    plural: 0,
    colour: 'white',
    type: ['normal'],
    gender: 'f',
    warmth: 3,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    outfitSecondary: ['upper', 'frilled sundress'],
    vagina_exposed: 0,
    anus_exposed: 0,
    cn_name_cap: '荷叶边夏日连衣裙',
    set: 'frilled sundress',
    colour_sidebar: 1,
    accessory_colour_sidebar: 0
  },
  halter_sundress_upper: {
    index: 123,
    slot: 'upper',
    name: 'halter sundress',
    variable: 'haltersundress',
    integrity: 100,
    reveal: 400,
    one_piece: 1,
    open: 0,
    state: 'waist',
    state_top: 'chest',
    plural: 0,
    colour: 'white',
    type: ['normal'],
    set: 'haltersundress',
    gender: 'f',
    warmth: 3,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    pregType: 0,
    colour_sidebar: 1,
    outfitPrimary: { lower: 'halter sundress skirt' },
    formfitting: 1,
    cn_name_cap: '露背夏日连衣裙',
    accessory_colour_sidebar: 0
  },
  halter_sundress_lower: {
    index: 112,
    slot: 'lower',
    name: 'halter sundress skirt',
    variable: 'haltersundress',
    integrity: 100,
    reveal: 400,
    one_piece: 1,
    state: 'waist',
    plural: 0,
    colour: 'white',
    type: ['normal'],
    set: 'haltersundress',
    gender: 'f',
    warmth: 3,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    outfitSecondary: ['upper', 'halter sundress'],
    back_img: 1,
    back_integrity_img: 1,
    rearresize: 0,
    skirt_down: 1,
    vagina_exposed: 0,
    anus_exposed: 0,
    high_img: 0,
    cn_name_cap: '露背夏日连衣裙',
    accessory_colour_sidebar: 0
  },
  open_shoulder_lolita_upper: {
    index: 127,
    slot: 'upper',
    name: 'open shoulder lolita dress',
    variable: 'openshoulderlolita',
    integrity: 70,
    reveal: 600,
    one_piece: 1,
    open: 0,
    state: 'waist',
    state_top: 'chest',
    plural: 0,
    colour: 'pink',
    type: ['normal'],
    set: 'openshoulderlolita',
    gender: 'f',
    warmth: 3,
    accessory: 1,
    accessory_colour: 'white',
    cursed: 0,
    location: 0,
    pregType: 'min',
    colour_sidebar: 1,
    outfitPrimary: { lower: 'lolita skirt' },
    accessory_colour_sidebar: 1,
    formfitting: 1,
    accessory_integrity_img: 1,
    sleeve_acc_img: 1,
    cn_name_cap: '露肩洛丽塔裙'
  },
  open_shoulder_lolita_lower: {
    index: 120,
    slot: 'lower',
    name: 'lolita skirt',
    variable: 'openshoulderlolita',
    integrity: 100,
    reveal: 400,
    one_piece: 1,
    state: 'waist',
    plural: 0,
    colour: 'pink',
    type: ['normal'],
    set: 'openshoulderlolita',
    gender: 'f',
    warmth: 3,
    accessory: 1,
    accessory_colour: 'white',
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    outfitSecondary: ['upper', 'open shoulder lolita dress'],
    accessory_colour_sidebar: 1,
    accessory_integrity_img: 1,
    back_img: 0,
    rearresize: 0,
    skirt_down: 1,
    vagina_exposed: 0,
    anus_exposed: 0,
    high_img: 0,
    cn_name_cap: '洛丽塔裙'
  },
  skimpy_lolita_upper: {
    index: 94,
    slot: 'upper',
    name: 'skimpy lolita dress',
    variable: 'skimpylolita',
    integrity: 70,
    reveal: 600,
    one_piece: 1,
    open: 0,
    state: 'waist',
    state_top: 'chest',
    plural: 0,
    colour: 'light pink',
    type: ['normal'],
    set: 'skimpylolita',
    gender: 'f',
    warmth: 4,
    accessory: 1,
    accessory_colour: 'white',
    cursed: 0,
    location: 0,
    pregType: 'min',
    colour_sidebar: 1,
    outfitPrimary: { lower: 'skimpy lolita skirt' },
    accessory_colour_sidebar: 1,
    sleeve_colour: 'secondary',
    cn_name_cap: '轻薄洛丽塔裙'
  },
  skimpy_lolita_lower: {
    index: 86,
    slot: 'lower',
    name: 'skimpy lolita skirt',
    variable: 'skimpylolita',
    integrity: 100,
    reveal: 400,
    one_piece: 1,
    state: 'waist',
    plural: 0,
    colour: 'light pink',
    type: ['normal'],
    set: 'skimpylolita',
    gender: 'f',
    warmth: 2,
    accessory: 1,
    accessory_colour: 'white',
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    outfitSecondary: ['upper', 'skimpy lolita dress'],
    accessory_colour_sidebar: 1,
    back_img: 0,
    rearresize: 0,
    skirt_down: 1,
    vagina_exposed: 0,
    anus_exposed: 0,
    high_img: 0,
    cn_name_cap: '轻薄洛丽塔裙'
  },
  denim_shorts: {
    index: 31,
    slot: 'lower',
    name: 'denim shorts',
    variable: 'jorts',
    integrity: 160,
    reveal: 500,
    one_piece: 0,
    state: 'waist',
    plural: 1,
    colour: 'light blue',
    exposed: 0,
    type: ['normal'],
    set: 'lower',
    gender: 'n',
    warmth: 2,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    colour_combat: 'blue',
    back_img: 0,
    rearresize: 0,
    skirt_down: 0,
    vagina_exposed: 0,
    anus_exposed: 0,
    high_img: 0,
    cn_name_cap: '牛仔短裤',
    accessory_colour_sidebar: 0,
    lastTaken: 'wardrobe'
  },
  checkered_skirt: {
    index: 203,
    slot: 'lower',
    name: 'checkered skirt',
    variable: 'checkered skirt',
    integrity: 100,
    reveal: 200,
    one_piece: 0,
    state: 'waist',
    plural: 0,
    colour: 'wine',
    exposed: 0,
    type: ['normal'],
    set: 'lower',
    gender: 'f',
    warmth: 1,
    accessory: 1,
    accessory_colour: 'black',
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    skirt_down: 1,
    vagina_exposed: 0,
    anus_exposed: 0,
    cn_name_cap: '格子裙',
    accessory_colour_sidebar: 1,
    accessory_integrity_img: 1,
    lastTaken: 'wardrobe'
  },
  t_shirt: {
    index: 4,
    slot: 'upper',
    name: 't-shirt',
    variable: 'tshirt',
    integrity: 100,
    reveal: 400,
    one_piece: 0,
    open: 0,
    state: 'waist',
    state_top: 'chest',
    plural: 0,
    colour: 'black',
    type: ['normal'],
    set: 'upper',
    gender: 'n',
    warmth: 5,
    accessory: 0,
    accessory_colour: 0,
    pregType: 0,
    colour_sidebar: 1,
    cn_name_cap: 'T恤衫',
    accessory_colour_sidebar: 0
  },
  band_t_shirt: {
    index: 119,
    slot: 'upper',
    name: 'band t-shirt',
    variable: 'band tee',
    integrity: 110,
    reveal: 300,
    one_piece: 0,
    open: 0,
    state: 'waist',
    state_top: 'chest',
    plural: 0,
    colour: 'white',
    exposed: 0,
    type: ['normal', 'cool', 'bellyHide'],
    set: 'upper',
    gender: 'm',
    warmth: 6,
    accessory: 1,
    accessory_colour: 'black',
    cursed: 0,
    location: 0,
    pregType: 0,
    colour_sidebar: 1,
    accessory_colour_sidebar: 1,
    accessory_integrity_img: 1,
    cn_name_cap: '乐队T恤衫',
    lastTaken: 'wardrobe'
  },
  boxy_t_shirt: {
    index: 120,
    slot: 'upper',
    name: 'boxy t-shirt',
    variable: 'boxy',
    integrity: 110,
    reveal: 300,
    one_piece: 0,
    open: 0,
    state: 'waist',
    state_top: 'chest',
    plural: 0,
    colour: 'white',
    exposed: 0,
    type: ['normal', 'bellyHide'],
    set: 'upper',
    gender: 'm',
    warmth: 6,
    accessory: 1,
    accessory_colour: 'white',
    cursed: 0,
    location: 0,
    pregType: 0,
    colour_sidebar: 1,
    accessory_colour_sidebar: 1,
    accessory_integrity_img: 1,
    cn_name_cap: '宽松T恤',
    lastTaken: 'wardrobe'
  },
  striped_panties: {
    index: 20,
    slot: 'under_lower',
    name: 'striped panties',
    variable: 'stripedpanties',
    integrity: 100,
    reveal: 500,
    one_piece: 0,
    state: 'waist',
    plural: 1,
    colour: 'red',
    exposed: 0,
    type: ['normal'],
    set: 'under_lower',
    gender: 'f',
    warmth: 1,
    accessory: 1,
    accessory_colour: 'black',
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    accessory_colour_sidebar: 1,
    rearresize: 0,
    vagina_exposed: 0,
    anus_exposed: 0,
    high_img: 0,
    name_simple: '内裤',
    anal_shield: 0,
    penis_img: 1,
    penis_acc_img: 1,
    cn_name_cap: '条纹内裤',
    lastTaken: 'wardrobe'
  },
  strawberry_slippers: {
    index: 83,
    slot: 'feet',
    name: 'strawberry slippers',
    variable: 'strawberryslippers',
    integrity: 100,
    reveal: 1,
    one_piece: 0,
    state: 0,
    plural: 1,
    colour: 'red',
    exposed: 0,
    type: ['sleep'],
    set: 'feet',
    gender: 'n',
    warmth: 2,
    accessory: 1,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    cn_name_cap: '草莓拖鞋',
    colour_sidebar: 1,
    accessory_colour_sidebar: 0,
    lastTaken: 'wardrobe'
  },
  school_shoes: {
    index: 1,
    slot: 'feet',
    name: 'school shoes',
    cn_name_cap: '校服鞋',
    variable: 'schoolshoes',
    state: 0,
    integrity: 200,
    reveal: 1,
    plural: 1,
    colour: 0,
    type: ['school'],
    gender: 'n',
    warmth: 2,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    colour_combat: 'black'
  },
  long_school_skirt: {
    index: 26,
    slot: 'lower',
    name: 'long school skirt',
    variable: 'schoolskirtlong',
    integrity: 120,
    reveal: 200,
    one_piece: 0,
    state: 'waist',
    plural: 0,
    colour: 'red',
    exposed: 0,
    type: ['school'],
    set: 'lower',
    gender: 'f',
    warmth: 3,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    vagina_exposed: 0,
    anus_exposed: 0,
    cn_name_cap: '长校服裙',
    accessory_colour_sidebar: 0,
    back_img: 0,
    high_img: 0,
    rearresize: 0,
    skirt_down: 1,
    lastTaken: 'wardrobe'
  },
  short_school_skirt: {
    index: 27,
    slot: 'lower',
    name: 'short school skirt',
    variable: 'schoolskirtshort',
    integrity: 80,
    reveal: 600,
    one_piece: 0,
    state: 'waist',
    plural: 0,
    colour: 'red',
    exposed: 0,
    type: ['school'],
    set: 'lower',
    gender: 'f',
    warmth: 1,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    accessory_colour_sidebar: 0,
    skirt_down: 1,
    vagina_exposed: 1,
    anus_exposed: 1,
    cn_name_cap: '短校服裙',
    back_img: 0,
    high_img: 0,
    rearresize: 0,
    lastTaken: 'wardrobe'
  }
} satisfies Record<string, ClothingItem>;
