import type { ClothingItem } from '../../module/NPCSidebarPortrait';

export const Clothing = {
  mini_snowman: {
    index: 37,
    slot: 'head',
    name: 'mini snowman',
    variable: 'minisnowman',
    integrity: 100,
    reveal: 1,
    one_piece: 0,
    state: 0,
    plural: 0,
    colour: 0,
    type: ['costume'],
    gender: 'n',
    warmth: 0,
    accessory: 0,
    accessory_colour: 0,
    colour_combat: 0,
    hood: 0,
    cn_name_cap: '小雪人',
    colour_sidebar: 0,
    accessory_colour_sidebar: 0
  },
  hairpin: {
    index: 1,
    slot: 'head',
    name: 'hairpin',
    cn_name_cap: '发卡',
    variable: 'hairpin',
    state: 0,
    integrity: 50,
    reveal: 1,
    plural: 0,
    colour: 'white',
    type: ['normal'],
    gender: 'f',
    warmth: 0,
    accessory: 1,
    accessory_colour: 'white',
    back_img: 0,
    cursed: 0,
    location: 0,
    accessory_colour_sidebar: 1,
    colour_combat: 0,
    colour_sidebar: 1
  },
  rose_eyepatch: {
    index: 46,
    slot: 'face',
    name: 'rose eyepatch',
    cn_name_cap: '玫瑰眼罩',
    variable: 'rose eyepatch',
    state: 0,
    integrity: 100,
    reveal: 200,
    plural: 0,
    colour: 'white',
    colour_sidebar: 1,
    type: ['formal', 'costume'],
    gender: 'n',
    warmth: 0,
    accessory: 1,
    accessory_colour: 'red',
    accessory_colour_sidebar: 1,
    altposition: 'none',
    altdisabled: [],
    cursed: 0,
    location: 0
  },
  flower_crown: {
    index: 14,
    slot: 'head',
    name: 'flower crown',
    cn_name_cap: '花环',
    variable: 'flower',
    state: 0,
    integrity: 50,
    reveal: 1,
    plural: 0,
    colour: 0,
    colour_combat: 0,
    type: ['normal'],
    gender: 'f',
    warmth: 0,
    accessory: 0,
    accessory_colour: 0,
    back_img: 'combat',
    cursed: 0,
    location: 0
  },
  glasses: {
    index: 1,
    slot: 'face',
    name: 'glasses',
    cn_name_cap: '眼镜',
    variable: 'glasses',
    state: 0,
    integrity: 20,
    reveal: 1,
    plural: 1,
    colour: 'red',
    colour_sidebar: 1,
    colour_combat: 0,
    type: ['glasses'],
    gender: 'n',
    warmth: 0,
    accessory: 1,
    accessory_colour: 0,
    altposition: 'none',
    altdisabled: [],
    cursed: 0,
    location: 0
  },
  holy_pendant: {
    index: 3,
    slot: 'neck',
    name: 'holy pendant',
    cn_name_cap: '十字架',
    variable: 'holypendant',
    state: 0,
    integrity: 100,
    reveal: 1,
    plural: 0,
    colour: 0,
    colour_combat: 'yellow',
    type: ['holy'],
    gender: 'n',
    warmth: 0,
    collared: 0,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0
  },
  school_shoes: {
    index: 1,
    slot: 'feet',
    name: 'school shoes',
    cn_name_cap: '校服鞋',
    variable: 'schoolshoes',
    state: 0,
    integrity: 200,
    reveal: 1,
    plural: 1,
    colour: 0,
    type: ['school'],
    gender: 'n',
    warmth: 2,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    colour_combat: 'black'
  },
  long_school_skirt: {
    index: 26,
    slot: 'lower',
    name: 'long school skirt',
    variable: 'schoolskirtlong',
    integrity: 120,
    reveal: 200,
    one_piece: 0,
    state: 'waist',
    plural: 0,
    colour: 'red',
    exposed: 0,
    type: ['school'],
    set: 'lower',
    gender: 'f',
    warmth: 3,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    vagina_exposed: 0,
    anus_exposed: 0,
    cn_name_cap: '长校服裙',
    accessory_colour_sidebar: 0,
    back_img: 0,
    high_img: 0,
    rearresize: 0,
    skirt_down: 1,
    lastTaken: 'wardrobe'
  },
  short_school_skirt: {
    index: 27,
    slot: 'lower',
    name: 'short school skirt',
    variable: 'schoolskirtshort',
    integrity: 80,
    reveal: 600,
    one_piece: 0,
    state: 'waist',
    plural: 0,
    colour: 'red',
    exposed: 0,
    type: ['school'],
    set: 'lower',
    gender: 'f',
    warmth: 1,
    accessory: 0,
    accessory_colour: 0,
    cursed: 0,
    location: 0,
    colour_sidebar: 1,
    accessory_colour_sidebar: 0,
    skirt_down: 1,
    vagina_exposed: 1,
    anus_exposed: 1,
    cn_name_cap: '短校服裙',
    back_img: 0,
    high_img: 0,
    rearresize: 0,
    lastTaken: 'wardrobe'
  }
} satisfies Record<string, ClothingItem>;
